name: Publish Snapshots

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Import GPG key
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      - name: Set up Maven global settings
        run: |
          echo "$MVN_GLOBAL_SETTINGS_XML" > ~/.m2/settings.xml
        env:
          MVN_GLOBAL_SETTINGS_XML: ${{ secrets.MVN_GLOBAL_SETTINGS_XML }}
      - name: Get Maven project version
        id: mvn-version
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Publish snapshot to GitHub Packages
        if: endsWith(steps.mvn-version.outputs.version, '-SNAPSHOT')
        run: mvn --batch-mode deploy -DskipTests
        env:
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
